#!/usr/bin/env bash
# This script that transfers a file from our client to a server
if [[ "$#" -ne 4 ]]
then
    echo "$0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
