#!/usr/bin/env bash
# This script Install nginx on your web-04
sudo  apt-get -y update
sudo  apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo chmod 644 /var/www/html/index.html

