#!/usr/bin/env bash
# This script Install nginx on your web-04
sudo  apt-get -y update
sudo  apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" var/www/html
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian-copy.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
sudo bash -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx restart

