#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
terminator() {
	rm /var/run/myscript.pid
	exit
}
echo "$$" > /var/run/myscript.pid
while :
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command" && terminator' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'terminator' SIGQUIT
done

