#!/usr/bin/env bash
# Display a header for the process list
pgrep -lf bash | while read -r line; do
    pid=$(echo "$line" | awk '{print $1}')
    process_name=$(echo "$line" | awk '{$1=""; print $0}')
    echo "$pid   $process_name"
done

